### ISSUE TITLE
24h Time in MOTD

### ISSUE THREAD

**Issue by robotter112** [Nincodedo/mc-server-description#2]
**Is your feature request related to a problem? Please describe.**
I use the mod on my server, and we play as a German community. Unfortunately, the 12-hour time system is not very common here.

**Describe the solution you'd like**
It would be very nice if you could set 12 / 24 hours in the Config.

**Comment by Nincodedo** [comment]
You'll need to add the config to the file yourself, but its `use24HourClock=true`. Released on Modrinth a few minutes ago. https://modrinth.com/mod/mc-server-description/version/4.2.0+1.20.1

**Comment by robotter112** [comment]
Many thanks for the quick implementation.
I will update it today and try it out.
