### ISSUE TITLE
24h time is counted incorrectly

### ISSUE THREAD

**Issue by robotter112** [Nincodedo/mc-server-description#3]
**Describe the bug**
The time is not reset at 23:59 and the day gets +1.
The time runs until 29:59 and then the day becomes +1 then the time starts at 06:00.

**To Reproduce**
Change the time in the config to 24H
`use24HourClock=true`

**Screenshots**
![stranded 2951](https://github.com/Nincodedo/mc-server-description/assets/55591181/a1e435d0-a9df-4b1b-a1b3-4cf62e6fe8ca)

![stranded 0600](https://github.com/Nincodedo/mc-server-description/assets/55591181/ffb0621a-b4dc-4f0c-b877-be33353abac4)

**Server (please complete the following information):**
 - OS: Debian 12
 - Minecraft: 1.20.2
 - Fabric: 0.15.3
 - Mod: 4.2.0

**Comment by Nincodedo** [comment]
Whoops, that's what I get for not testing this enough. I'll have a fix out in a bit.
