### ISSUE TITLE
Day counter counts incorrectly

### ISSUE THREAD

**Issue by robotter112** [Nincodedo/mc-server-description#4]
**Describe the bug**
The day only gets +1 when it becomes 06:00, not at 00:00.

**To Reproduce**
Change the time in the config to 24H
use24HourClock=true

**Screenshots**
![stranded 0506](https://github.com/Nincodedo/mc-server-description/assets/55591181/95f473c4-7104-4741-a409-68e6e20f8a0c)

![stranded 0607](https://github.com/Nincodedo/mc-server-description/assets/55591181/54e5b78b-f85c-47d2-ac81-5e939a8b343a)

**Server (please complete the following information):**

- OS: Debian 12
- Minecraft: 1.20.2
-  Fabric: 0.15.3
- Mod: 4.2.1

**Comment by Nincodedo** [comment]
That is how Minecraft counts days. The day number doesn't roll over at midnight. It rolls over after the sun is up for a bit. https://minecraft.wiki/w/Daylight_cycle#Daytime

**Comment by robotter112** [comment]
Okay, I didn't know that. Then everything works fine now, thank you very much.
